# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1367, 768)
        MainWindow.setStyleSheet("background-color: rgb(179, 203, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 270, 1341, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_letters = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_letters.setEnabled(True)
        self.label_letters.setText("")
        self.label_letters.setAlignment(QtCore.Qt.AlignCenter)
        self.label_letters.setObjectName("label_letters")
        self.verticalLayout_9.addWidget(self.label_letters)
        self.gridLayout.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_digram = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_digram.setText("")
        self.label_digram.setAlignment(QtCore.Qt.AlignCenter)
        self.label_digram.setObjectName("label_digram")
        self.verticalLayout.addWidget(self.label_digram)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_trigram = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_trigram.setText("")
        self.label_trigram.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trigram.setObjectName("label_trigram")
        self.verticalLayout_12.addWidget(self.label_trigram)
        self.gridLayout.addLayout(self.verticalLayout_12, 2, 2, 1, 1)
        self.theBestLang = QtWidgets.QLabel(self.centralwidget)
        self.theBestLang.setGeometry(QtCore.QRect(710, 695, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.theBestLang.setFont(font)
        self.theBestLang.setText("")
        self.theBestLang.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.theBestLang.setObjectName("theBestLang")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 1341, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255); \n"
"background-color: rgb(28, 80, 62);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.textToAnalize = QtWidgets.QTextBrowser(self.centralwidget)
        self.textToAnalize.setGeometry(QtCore.QRect(10, 50, 1341, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textToAnalize.setFont(font)
        self.textToAnalize.setStyleSheet("background-color: rgb(243, 235, 240);")
        self.textToAnalize.setObjectName("textToAnalize")
        self.showLangBT = QtWidgets.QPushButton(self.centralwidget)
        self.showLangBT.setGeometry(QtCore.QRect(280, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.showLangBT.setFont(font)
        self.showLangBT.setStyleSheet("background-color: rgb(28, 80, 62);\n"
"color: rgb(255, 255, 255); ")
        self.showLangBT.setObjectName("showLangBT")
        self.textLang = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLang.setGeometry(QtCore.QRect(460, 200, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(True)
        self.textLang.setFont(font)
        self.textLang.setStyleSheet("background-color: rgb(239, 231, 236);")
        self.textLang.setObjectName("textLang")
        self.generatePlotsBT = QtWidgets.QPushButton(self.centralwidget)
        self.generatePlotsBT.setGeometry(QtCore.QRect(830, 200, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.generatePlotsBT.setFont(font)
        self.generatePlotsBT.setStyleSheet("background-color: rgb(28, 80, 62);\n"
"color: rgb(255, 255, 255); ")
        self.generatePlotsBT.setObjectName("generatePlotsBT")
        self.enlargeLettersBT = QtWidgets.QPushButton(self.centralwidget)
        self.enlargeLettersBT.setGeometry(QtCore.QRect(160, 620, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.enlargeLettersBT.setFont(font)
        self.enlargeLettersBT.setStyleSheet("background-color: rgb(28, 80, 62);\n"
"color: rgb(255, 255, 255); ")
        self.enlargeLettersBT.setObjectName("enlargeLettersBT")
        self.enlargeDigramsBT = QtWidgets.QPushButton(self.centralwidget)
        self.enlargeDigramsBT.setGeometry(QtCore.QRect(620, 620, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.enlargeDigramsBT.setFont(font)
        self.enlargeDigramsBT.setStyleSheet("background-color: rgb(28, 80, 62);\n"
"color: rgb(255, 255, 255); ")
        self.enlargeDigramsBT.setObjectName("enlargeDigramsBT")
        self.enlargeTrigramsBT = QtWidgets.QPushButton(self.centralwidget)
        self.enlargeTrigramsBT.setGeometry(QtCore.QRect(1070, 620, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.enlargeTrigramsBT.setFont(font)
        self.enlargeTrigramsBT.setStyleSheet("background-color: rgb(28, 80, 62);\n"
"color: rgb(255, 255, 255); ")
        self.enlargeTrigramsBT.setObjectName("enlargeTrigramsBT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1367, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Analiza tekstu"))
        self.showLangBT.setText(_translate("MainWindow", "Wykryj język"))
        self.generatePlotsBT.setText(_translate("MainWindow", "Generuj wykresy"))
        self.enlargeLettersBT.setText(_translate("MainWindow", "Powiększ"))
        self.enlargeDigramsBT.setText(_translate("MainWindow", "Powiększ"))
        self.enlargeTrigramsBT.setText(_translate("MainWindow", "Powiększ"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
